In [1]:
import numpy as np

In [2]:
salarios = np.genfromtxt('datos/salary.csv', delimiter=',')
salarios

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [3]:
salarios.max()

850000.0

In [4]:
np.argmax(salarios)

246

In [5]:
np.argmin(salarios)

282

In [6]:
salarios[282]

11400.0

In [7]:
np.argsort(salarios)

array([282, 969, 606, ..., 829, 389, 246], dtype=int64)

In [8]:
np.argsort(salarios, kind="mergesort")

array([282, 969, 606, ..., 829, 389, 246], dtype=int64)

In [10]:
indices_mayores_a_cincuentamil = np.where(salarios > 50000)
indices_mayores_a_cincuentamil

(array([   0,    1,    2,    3,    4,    9,   15,   21,   22,   24,   27,
          28,   29,   31,   32,   33,   34,   36,   37,   38,   42,   44,
          45,   46,   48,   49,   51,   52,   55,   59,   60,   67,   68,
          69,   75,   77,   78,   79,   81,   83,   84,   87,   88,   91,
          92,   94,   95,   96,   97,  102,  105,  106,  107,  109,  110,
         111,  115,  117,  118,  119,  123,  125,  127,  139,  142,  146,
         151,  153,  156,  158,  161,  162,  172,  173,  177,  178,  182,
         183,  185,  192,  193,  194,  195,  196,  197,  198,  202,  212,
         216,  217,  220,  221,  233,  234,  236,  237,  238,  239,  241,
         242,  243,  244,  246,  249,  252,  256,  257,  260,  270,  271,
         273,  277,  278,  280,  281,  283,  286,  288,  289,  290,  292,
         293,  295,  296,  297,  300,  301,  302,  303,  305,  306,  311,
         312,  315,  316,  321,  322,  326,  329,  332,  333,  334,  335,
         337,  339,  343,  344,  346,  348,  350,  353,  360,  362,  365,
         369,  370,  373,  378,  381,  384,  385,  388,  389,  395,  396,
         402,  406,  408,  409,  413,  419,  422,  428,  429,  431,  432,
         433,  436,  437,  439,  441,  442,  443,  446,  450,  453,  454,
         455,  458,  459,  465,  466,  467,  471,  473,  475,  476,  482,
         484,  486,  488,  490,  491,  493,  496,  502,  503,  504,  508,
         510,  511,  512,  514,  515,  516,  517,  518,  520,  522,  523,
         527,  530,  535,  537,  538,  539,  543,  544,  545,  552,  553,
         556,  559,  560,  562,  563,  565,  566,  570,  571,  575,  577,
         579,  580,  581,  582,  585,  594,  596,  599,  600,  602,  603,
         607,  611,  612,  614,  615,  616,  623,  624,  626,  627,  628,
         634,  637,  638,  642,  644,  645,  647,  649,  650,  651,  652,
         657,  660,  661,  662,  664,  669,  676,  679,  681,  682,  684,
         687,  689,  690,  691,  697,  699,  701,  702,  703,  705,  706,
         712,  716,  718,  719,  720,  725,  728,  736,  737,  738,  740,
         741,  742,  745,  746,  747,  752,  757,  758,  763,  765,  766,
         769,  773,  774,  776,  777,  778,  779,  781,  783,  789,  790,
         791,  793,  794,  799,  800,  801,  802,  804,  805,  807,  809,
         812,  813,  815,  816,  817,  818,  819,  820,  822,  824,  826,
         827,  828,  829,  831,  833,  837,  841,  842,  848,  850,  852,
         854,  859,  862,  863,  866,  867,  872,  873,  876,  878,  881,
         882,  888,  890,  891,  893,  895,  897,  899,  901,  902,  908,
         912,  913,  914,  918,  922,  926,  929,  934,  938,  939,  945,
         946,  949,  950,  952,  958,  961,  963,  965,  966,  967,  970,
         971,  973,  974,  977,  978,  979,  980,  982,  983,  986,  992,
         998,  999, 1004, 1006, 1008, 1010, 1012, 1015, 1016, 1017, 1018,
        1019, 1026, 1027, 1030, 1032, 1033, 1037, 1040, 1041, 1049, 1051,
        1052, 1053, 1055, 1060, 1062, 1063, 1065, 1068, 1074, 1079, 1086,
        1087, 1088, 1092, 1094, 1097, 1104, 1105, 1107, 1109, 1110, 1112,
        1116, 1117, 1118, 1126, 1127, 1129, 1130, 1132, 1134, 1137, 1142,
        1143, 1144, 1146], dtype=int64),)

In [13]:
salarios[indices_mayores_a_cincuentamil]
condicion_media = salarios > np.mean(salarios)
condicion_media

array([ True,  True,  True, ..., False, False,  True])

In [14]:
salarios[condicion_media]

array([ 60000.,  58000.,  56967.,  70000.,  75000.,  62000.,  56000.,
       261546.,  77000., 500000.,  77570.,  60000.,  65000.,  60000.,
       120000.,  81000.,  75000.,  75000.,  73000.,  75000., 210000.,
        90000., 105227.,  84000.,  98000.,  70000., 115000.,  72000.,
        57400.,  70000.,  71796., 130773., 103529.,  57000.,  70000.,
        75000.,  57000., 119875.,  60000., 132000., 100000., 141671.,
        87500.,  90000.,  65000., 109100.,  98080.,  87689., 550000.,
        56697.,  60000., 180000.,  92000.,  63000., 220000.,  66000.,
        80000.,  65460.,  65000., 109294.,  70000.,  57758.,  75000.,
        75000.,  62662.,  64000.,  90000.,  60000.,  60000.,  70000.,
        63000.,  80000.,  70000.,  60000.,  90000., 135380.,  65000.,
        70000., 103529.,  64000.,  70000., 120000., 185000.,  70000.,
       850000.,  61500.,  60000.,  63000., 181339.,  75665.,  58000.,
        57000., 100000.,  65000.,  62662.,  90000.,  70835.,  75000.,
       111600., 102000.,  60000.,  65000., 625000., 100000.,  78000.,
        75000.,  60000.,  64000.,  63000.,  59656.,  69000.,  80750.,
        84703., 110464., 102000.,  56732.,  63000.,  62000.,  60000.,
        70151.,  60000.,  56400.,  65000., 140000.,  75000.,  65000.,
       120000., 820000.,  80000., 250000.,  58000., 130000.,  85000.,
        60000.,  65000.,  71925., 136375.,  90000., 141000.,  90000.,
        65000.,  66000.,  72000.,  65000., 142800.,  68000., 116626.,
        65000.,  56000.,  57758.,  58000.,  60000.,  60000.,  97000.,
        67382.,  90000.,  85000.,  75000.,  57000.,  60000.,  76600.,
        60000., 110000., 130000.,  61398.,  60000.,  65000.,  70000.,
       100000.,  59000.,  57000.,  60000.,  76000.,  60000.,  88000.,
       444000.,  59000.,  70000.,  72000., 100000.,  70000., 116000.,
        65000., 110000.,  70000.,  82000.,  56000.,  60000.,  72000.,
        60000.,  70000., 113996., 160000.,  60000.,  81733.,  66000.,
        80000.,  66000., 150000.,  56000., 108000.,  62031., 100000.,
        60000.,  68000.,  60000.,  60000.,  60000.,  90000.,  61700.,
        75000.,  77000.,  96000.,  60000.,  86000.,  68000.,  63000.,
        65000.,  60000.,  90000.,  90000.,  80000.,  63000.,  80000.,
        70915., 120000.,  73500.,  60000.,  60000., 120000.,  56000.,
        84396.,  95000.,  94704.,  71000.,  70000.,  60000., 220000.,
       117701.,  57758.,  80000.,  65000.,  72000.,  70000., 120000.,
        60000.,  60000.,  63500.,  60000.,  59640.,  61027.,  70000.,
        61800., 120010.,  83500.,  75000.,  72000.,  84000., 110000.,
        60005.,  59500.,  70518.,  66000.,  58000.,  70000.,  99500.,
        66858., 103645.,  77000.,  56000.,  62000.,  60000.,  57400.,
        92735.,  58000.,  69000., 102000.,  68000., 108977.,  75653.,
        68000.,  59938., 680000.,  56967.,  57600.,  75000.,  60000.,
        60000.,  58000., 152568.,  98324.,  65000.,  63605.,  82000.,
        57000.,  62000.,  85000.,  60000.,  62500.,  68656.,  87280.,
        60000.,  57400.,  76000.,  63207.,  59000., 114800.,  60000.,
        72000., 150000.,  70000.,  60000.,  57000.,  70000.,  59938.,
       111841., 110000.,  63000.,  63207.,  59000.,  64000.,  58000.,
        75000.,  75000.,  70500.,  61000.,  60555., 108000.,  60000.,
        80000., 102000., 100000.,  64800.,  62000., 134449.,  75000.,
        70000.,  65000.,  94000.,  65000.,  60000., 120000.,  80000.,
        95000.,  65000., 101349.,  74000.,  70000.,  76289.,  95000.,
        78000.,  72000.,  92000.,  65000., 120000.,  72000., 250000.,
        68500.,  62000.,  81000.,  70000.,  84000.,  56000.,  87689.,
       175000., 261546.,  59000.,  56000., 120000.,  82000.,  70000.,
        71380.,  62000., 100000.,  80000., 103000.,  57000.,  76800.,
        75000.,  90000.,  70000.])

In [15]:
np.extract(condicion_media, salarios)

array([ 60000.,  58000.,  56967.,  70000.,  75000.,  62000.,  56000.,
       261546.,  77000., 500000.,  77570.,  60000.,  65000.,  60000.,
       120000.,  81000.,  75000.,  75000.,  73000.,  75000., 210000.,
        90000., 105227.,  84000.,  98000.,  70000., 115000.,  72000.,
        57400.,  70000.,  71796., 130773., 103529.,  57000.,  70000.,
        75000.,  57000., 119875.,  60000., 132000., 100000., 141671.,
        87500.,  90000.,  65000., 109100.,  98080.,  87689., 550000.,
        56697.,  60000., 180000.,  92000.,  63000., 220000.,  66000.,
        80000.,  65460.,  65000., 109294.,  70000.,  57758.,  75000.,
        75000.,  62662.,  64000.,  90000.,  60000.,  60000.,  70000.,
        63000.,  80000.,  70000.,  60000.,  90000., 135380.,  65000.,
        70000., 103529.,  64000.,  70000., 120000., 185000.,  70000.,
       850000.,  61500.,  60000.,  63000., 181339.,  75665.,  58000.,
        57000., 100000.,  65000.,  62662.,  90000.,  70835.,  75000.,
       111600., 102000.,  60000.,  65000., 625000., 100000.,  78000.,
        75000.,  60000.,  64000.,  63000.,  59656.,  69000.,  80750.,
        84703., 110464., 102000.,  56732.,  63000.,  62000.,  60000.,
        70151.,  60000.,  56400.,  65000., 140000.,  75000.,  65000.,
       120000., 820000.,  80000., 250000.,  58000., 130000.,  85000.,
        60000.,  65000.,  71925., 136375.,  90000., 141000.,  90000.,
        65000.,  66000.,  72000.,  65000., 142800.,  68000., 116626.,
        65000.,  56000.,  57758.,  58000.,  60000.,  60000.,  97000.,
        67382.,  90000.,  85000.,  75000.,  57000.,  60000.,  76600.,
        60000., 110000., 130000.,  61398.,  60000.,  65000.,  70000.,
       100000.,  59000.,  57000.,  60000.,  76000.,  60000.,  88000.,
       444000.,  59000.,  70000.,  72000., 100000.,  70000., 116000.,
        65000., 110000.,  70000.,  82000.,  56000.,  60000.,  72000.,
        60000.,  70000., 113996., 160000.,  60000.,  81733.,  66000.,
        80000.,  66000., 150000.,  56000., 108000.,  62031., 100000.,
        60000.,  68000.,  60000.,  60000.,  60000.,  90000.,  61700.,
        75000.,  77000.,  96000.,  60000.,  86000.,  68000.,  63000.,
        65000.,  60000.,  90000.,  90000.,  80000.,  63000.,  80000.,
        70915., 120000.,  73500.,  60000.,  60000., 120000.,  56000.,
        84396.,  95000.,  94704.,  71000.,  70000.,  60000., 220000.,
       117701.,  57758.,  80000.,  65000.,  72000.,  70000., 120000.,
        60000.,  60000.,  63500.,  60000.,  59640.,  61027.,  70000.,
        61800., 120010.,  83500.,  75000.,  72000.,  84000., 110000.,
        60005.,  59500.,  70518.,  66000.,  58000.,  70000.,  99500.,
        66858., 103645.,  77000.,  56000.,  62000.,  60000.,  57400.,
        92735.,  58000.,  69000., 102000.,  68000., 108977.,  75653.,
        68000.,  59938., 680000.,  56967.,  57600.,  75000.,  60000.,
        60000.,  58000., 152568.,  98324.,  65000.,  63605.,  82000.,
        57000.,  62000.,  85000.,  60000.,  62500.,  68656.,  87280.,
        60000.,  57400.,  76000.,  63207.,  59000., 114800.,  60000.,
        72000., 150000.,  70000.,  60000.,  57000.,  70000.,  59938.,
       111841., 110000.,  63000.,  63207.,  59000.,  64000.,  58000.,
        75000.,  75000.,  70500.,  61000.,  60555., 108000.,  60000.,
        80000., 102000., 100000.,  64800.,  62000., 134449.,  75000.,
        70000.,  65000.,  94000.,  65000.,  60000., 120000.,  80000.,
        95000.,  65000., 101349.,  74000.,  70000.,  76289.,  95000.,
        78000.,  72000.,  92000.,  65000., 120000.,  72000., 250000.,
        68500.,  62000.,  81000.,  70000.,  84000.,  56000.,  87689.,
       175000., 261546.,  59000.,  56000., 120000.,  82000.,  70000.,
        71380.,  62000., 100000.,  80000., 103000.,  57000.,  76800.,
        75000.,  90000.,  70000.])